# Generated by Django 5.1.6 on 2025-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('wins', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
            ],
        ),
    ]
