version: '3.8'
services:
  db:
    image: postgres
    restart: always
    user: "${UID}:${GID}"
    environment:
      POSTGRES_DB: pongdb
      POSTGRES_USER: ponguser
      POSTGRES_PASSWORD: WillowRapids
    ports:
      - "5432:5432"
    volumes:
      - /goinfre/${USER}/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponguser -d pongdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    user: "${UID}:${GID}"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
    volumes:
      - /goinfre/${USER}/pong/certs:/app/certs:ro
      - ./backend:/app
    environment:
      - SSL_ENABLED=true  # Set to true when certificates are ready
      - SSL_CERT_FILE=./certs/cert.pem
      - SSL_KEY_FILE=./certs/key.pem
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=pongdb
      - POSTGRES_USER=ponguser
      - POSTGRES_PASSWORD=WillowRapids
    command: ["/bin/bash", "start.sh"]

  frontend:
    image: nginx
    user: "${UID}:${GID}"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /goinfre/${USER}/pong/certs:/etc/nginx/certs:ro
    ports:
      - "8001:80"   # HTTP
      - "8444:443"  # HTTPS
    depends_on:
      - backend

volumes:
  postgres_data:
    driver_opts:
      type: none
      device: /goinfre/${USER}/postgres_data
      o: bind