global:
  resolve_timeout: 5m
  # In production, configure smtp settings
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_auth_username: 'username'
  # smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'web-hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web-hook'
    webhook_configs:
      - url: 'http://localhost:8080/alert'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/critical-alert'
        send_resolved: true
    # In production, uncomment and configure email settings
    # email_configs:
    #  - to: 'admin@example.com'
    #    send_resolved: true

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:8080/warning-alert'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']